<script>
  export let id = 'compression';
  import ThreeLayer from '../ui/ThreeLayer.svelte';
  import FormulaBlock from '../ui/FormulaBlock.svelte';
  import Citation from '../ui/Citation.svelte';
  import GlossaryTerm from '../ui/GlossaryTerm.svelte';
</script>

<section {id} class="section-card">
  <h2 class="section-title">Compression, Complexity, and Scaling</h2>

  <p>
    Universal scaling laws are, at their core, statements about compressibility. A trajectory that follows a
    <GlossaryTerm term="power law" definition="A scale-free relationship f(x) ∝ xᵅ — the same structure at every scale." />
    can be described by a tiny program — a few parameters fully specify its infinite evolution. A random trajectory cannot be compressed. This connection between
    <GlossaryTerm term="Kolmogorov complexity" definition="K(x) — the length of the shortest program that produces string x on a universal Turing machine. The fundamental measure of algorithmic information content." />
    and dynamical regularity runs directly into modern neural scaling laws.
  </p>

  <ThreeLayer section="compression">
    <svelte:fragment slot="conceptual">
      <p>Kolmogorov complexity K(x) is the length of the shortest computer program that outputs the string x. Lawful sequences — those generated by simple rules — have low K: the program is just the rule. Random sequences have K ≈ |x|: no compression is possible.</p>
      <p style="margin-top: 0.8em;">A power-law NADC has low K: the entire trajectory is specified by its exponent β and amplitude A. A trajectory that meanders without a convergence law is high-K: only by storing the trajectory itself can you reproduce it.</p>
      <p style="margin-top: 0.8em;">Large language models learn compressed representations of natural language. Neural scaling laws — the fact that loss decreases as a power law of training compute — suggest that natural language has low effective K: structured data compresses well under gradient descent.</p>
    </svelte:fragment>

    <svelte:fragment slot="technical">
      <FormulaBlock
        formula="K(x) = min&#123; |p| : U(p) = x &#125;"
        symbols={[
          {sym:'K(x)',meaning:'Kolmogorov complexity of string x'},
          {sym:'p',meaning:'a program for universal Turing machine U'},
          {sym:'|p|',meaning:'length of program p in bits'},
          {sym:'U(p) = x',meaning:'U outputs x when run on input p'},
        ]}
        derivation="Defined by Kolmogorov (1965) and Solomonoff (1964). K(x) is uncomputable in general (by reduction from the halting problem), but upper bounds are computable via any compressor. Invariance theorem: K_U(x) and K_V(x) differ by at most a constant depending on U and V."
        validity="Defined up to an additive constant depending on the choice of universal Turing machine. Practical compressors (gzip, bz2) give computable upper bounds."
        example="String '010101...01' (100 repetitions): K(x) ≈ log₂(100) + O(1) ≈ 7 bits. Random 800-bit string: K(x) ≈ 800 bits. Power-law sequence dₙ = n⁻¹ to n=1000: K ≈ O(log 1000) ≈ 10 bits — 100× more compressible than random."
      />
      <p style="margin-top: 0.8em;"><strong>Why power-law NADCs are compressible:</strong> A trajectory (d₁, d₂, ..., dₙ) following d(n) = A·n<sup>-β</sup> requires only two numbers (A, β) to reconstruct regardless of n. Its Kolmogorov complexity is O(log n) — logarithmic in sequence length. A random sequence of the same length has K ≈ n log|alphabet|. <Citation key="kolmogorov1965" /></p>
      <p style="margin-top: 0.8em;"><strong>Connection to neural scaling laws</strong> <Citation key="kaplan2020" /> <Citation key="hoffmann2022" />: The loss function L(C) ∝ C<sup>−α</sup> implies that as compute increases, the model learns increasingly low-K descriptions of the data. The power-law form of the scaling law is itself evidence that natural language has a hierarchical, self-similar structure amenable to compression. If data distribution P has effective complexity K(P) = κ, and model capacity is C, then under suitable assumptions L ∝ (κ/C)<sup>α</sup> — a compression ratio.</p>
    </svelte:fragment>

    <svelte:fragment slot="computational">
      <pre style="background: var(--formula-bg); padding: 14px; border-radius: 4px; font-size: 0.82em; overflow-x: auto;">import gzip
import numpy as np

def compress_ratio(seq):
    """Estimate compressibility via gzip. Lower = more compressible."""
    b = ' '.join(f'&#123;x:.4f&#125;' for x in seq).encode()
    return len(gzip.compress(b)) / len(b)

n = np.arange(1, 501)

power_law  = 3.0 * n**(-1.0)
exponential = 3.0 * np.exp(-0.05 * n)
random_seq = np.cumsum(np.random.randn(500)) * 0.01

print(f"Power law compression ratio:   &#123;compress_ratio(power_law):.3f&#125;")
print(f"Exponential compression ratio: &#123;compress_ratio(exponential):.3f&#125;")
print(f"Random walk compression ratio: &#123;compress_ratio(random_seq):.3f&#125;")
# Expected: power_law ≈ 0.15, exponential ≈ 0.14, random ≈ 0.85
# Power-law and exponential are ~6x more compressible than random</pre>
    </svelte:fragment>
  </ThreeLayer>
</section>
